# Generated by Django 2.2.6 on 2020-08-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='ReasonPass',
            field=models.CharField(default='', max_length=200, verbose_name='Reason for Pass'),
        ),
    ]
