# Generated by Django 2.2.6 on 2020-09-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManager', '0008_auto_20200912_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='PassCodePointer',
            field=models.CharField(default=41, max_length=5),
            preserve_default=False,
        ),
    ]
