# Generated by Django 2.2.6 on 2020-09-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManager', '0009_checkin_passcodepointer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='PassCodePointer',
            field=models.IntegerField(max_length=5),
        ),
    ]
