# Generated by Django 2.2.6 on 2020-09-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManager', '0010_auto_20200918_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PassCodePointer', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='PassCodePointer',
        ),
    ]
