# Generated by Django 2.2.6 on 2020-09-18 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManager', '0011_auto_20200918_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointers',
            name='Season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StudentManager.Seasons'),
        ),
    ]
