# Generated by Django 2.2.6 on 2020-09-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManager', '0012_pointers_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='ByStaff',
            new_name='ByStaffCheckIn',
        ),
        migrations.AddField(
            model_name='checkin',
            name='ByStaffPass',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Checked-In By'),
        ),
    ]
