# Generated by Django 2.2.6 on 2020-09-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManager', '0014_account_admin_gate_schooladmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastoral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
