# Generated by Django 2.2.6 on 2020-09-12 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StudentManager', '0008_auto_20200912_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalInbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.CharField(blank=True, max_length=4, null=True, verbose_name='Viewed')),
                ('approved', models.CharField(blank=True, max_length=4, null=True, verbose_name='Approved')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManager.Students', verbose_name='Student')),
            ],
        ),
    ]
